# Generated by Django 3.0.3 on 2020-04-08 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Emp_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('First_name', models.CharField(max_length=20)),
                ('Middle_name', models.CharField(max_length=10)),
                ('Last_name', models.CharField(max_length=10)),
                ('Father_name', models.CharField(max_length=20)),
                ('Mother_name', models.CharField(max_length=20)),
                ('Emp_DOB', models.DateField()),
                ('Emp_Temp_Address', models.TextField(blank=True)),
                ('Emp_Perm_Address', models.TextField(blank=True)),
                ('Gender', models.CharField(max_length=10)),
                ('contact_no', models.IntegerField(unique=True)),
                ('aadhar_no', models.IntegerField()),
                ('pan_no', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='emp_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Employee2',
            fields=[
                ('Emp_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=20)),
                ('Middle_name', models.CharField(max_length=10)),
                ('Last_name', models.CharField(max_length=10)),
                ('Father_name', models.CharField(max_length=20)),
                ('Mother_name', models.CharField(max_length=20)),
                ('Emp_DOB', models.DateField()),
                ('Emp_Temp_Address', models.TextField(blank=True)),
                ('Emp_Perm_Address', models.TextField(blank=True)),
                ('Gender', models.CharField(max_length=10)),
                ('contact_no', models.IntegerField(unique=True)),
                ('aadhar_no', models.IntegerField(unique=True)),
                ('pan_no', models.CharField(max_length=10, unique=True)),
                ('image', models.ImageField(unique=True, upload_to='emp_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Education_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tenth_marks_memo', models.FileField(unique=True, upload_to='Tenth_marks_memo/')),
                ('Intermediate_marks_memo', models.FileField(unique=True, upload_to='Intermediate_marks_memo/')),
                ('Diploma1_marks_memo', models.FileField(unique=True, upload_to='Diploma1_marks_memo/')),
                ('Diploma2_marks_memo', models.FileField(unique=True, upload_to='Diploma2_marks_memo/')),
                ('Diploma3_marks_memo', models.FileField(unique=True, upload_to='Diploma3_marks_memo/')),
                ('Graduation_marks_memo', models.FileField(unique=True, upload_to='graduation_marks_memo/')),
                ('Post_Graduation_marks_memo', models.FileField(unique=True, upload_to='postgraduation_marks_memo/')),
                ('identity_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_hrm.Employee2')),
            ],
        ),
    ]
